creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: E550B5F0D060DB3BA042EE9EA758B8B5C5A4ED36
  path_regex: base/.*
