apiVersion: v1
kind: Namespace
metadata:
  name: bigbang
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 10m
  url: https://repo1.dso.mil/big-bang/customers/technical-profiles.git
  ref:
    branch: initial-customer-template
  secretRef:
    name: private-git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./default-profile
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
